# Generated by Django 5.2 on 2025-05-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_property_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
