# Generated by Django 5.2 on 2025-05-22 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_propertyimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyimage',
            old_name='property',
            new_name='listing',
        ),
    ]
